package server

import "net/http"

// openAPIOperation is one path+method entry in the hand-written doc below.
// Full request/response schemas aren't required by the brief — this is
// enough for a client (or `ensemble api --json` passthrough) to discover
// what's available and how to call it.
type openAPIOperation struct {
	Summary string `json:"summary"`
}

type openAPIPathItem map[string]openAPIOperation // method (lowercase) -> operation

// buildOpenAPI returns a minimal OpenAPI 3.1 document listing every
// endpoint this package serves. Hand-written and regenerated by hand when
// routes.go changes — no reflection/codegen dependency.
func buildOpenAPI(version string) map[string]any {
	paths := map[string]openAPIPathItem{
		"/api/health":   {"get": {Summary: "Liveness and version"}},
		"/api/status":   {"get": {Summary: "Orchestrator states and proxy ports"}},
		"/api/topology": {"get": {Summary: "Nodes (services/databases/stubs) and dependency/proxy-wiring edges"}},

		"/api/services/{name}/restart": {"post": {Summary: "Restart a service, preserving its current placement"}},
		"/api/services/{name}/flip":    {"post": {Summary: "Flip a service between native and container placement"}},

		"/api/seed/{name}": {"post": {Summary: "Run a named seed's SQL and HTTP steps"}},

		"/api/traffic":        {"get": {Summary: "Recorded hops, filterable by since/limit/errorsOnly/session"}},
		"/api/traffic/stream": {"get": {Summary: "Server-Sent Events stream of hops, replaying from ?since="}},

		"/api/traces/{traceId}":        {"get": {Summary: "A trace's hops plus its collapsed logical view"}},
		"/api/traces/{traceId}/export": {"get": {Summary: "Export a trace as HAR, curl commands, or raw HTTP text"}},

		"/api/latency": {
			"get":    {Summary: "List latency injection rules"},
			"put":    {Summary: "Upsert a latency rule keyed by (target, path)"},
			"delete": {Summary: "Remove a latency rule by ?target=&path="},
		},
		"/api/latency/arm-all": {"post": {Summary: "Enable/disable every latency rule"}},
		"/api/latency/reset":   {"post": {Summary: "Remove every latency rule"}},

		"/api/sessions": {"post": {Summary: "Start a recording session against an entry service"}},
		"/api/sessions/{id}": {
			"delete": {Summary: "End a session; returns its hop count and capture-trust verdict"},
		},
		"/api/sessions/{id}/hops": {"get": {Summary: "NDJSON dump of an active session's hops so far"}},

		"/api/openapi.json": {"get": {Summary: "This document"}},

		"/api/shutdown": {"post": {Summary: "Gracefully stop the ensemble process (loopback only)"}},
	}

	return map[string]any{
		"openapi": "3.1.0",
		"info": map[string]any{
			"title":   "ensemble control plane",
			"version": version,
		},
		"paths": paths,
	}
}

func (s *server) handleOpenAPI(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, buildOpenAPI(s.Version))
}
